'use client'

import type { PhProduct, Founder } from '@/lib/fixtures/types'
import DecodePreviewCard from './DecodePreviewCard'
import RapidCoursePreviewCard from './RapidCoursePreviewCard'

interface CommunityProfileProps {
  product: PhProduct
  founder: Founder | null
}

export default function CommunityProfile({ product, founder }: CommunityProfileProps) {
  return (
    <div className="flex gap-10 fade-up">
      {/* Left column — fixed identity panel */}
      <div className="w-[40%] shrink-0">
        <div className="sticky top-28">
          {/* Product logo */}
          <div className="w-24 h-24 rounded-2xl overflow-hidden shadow-lg border border-orange-100/40 mb-5 bg-white">
            <img src={product.logo} alt={`${product.name} logo`} className="w-full h-full object-cover" />
          </div>

          {/* Name + tagline */}
          <h1 className="text-3xl font-black font-jakarta text-primary leading-tight mb-1">
            {product.name}
          </h1>
          {product.tagline && (
            <p className="text-base text-on-background/70 mb-4">{product.tagline}</p>
          )}

          {/* Category pill */}
          <span
            className="inline-block text-xs font-bold rounded-full px-4 py-1.5 mb-5"
            style={{
              background: 'linear-gradient(135deg, rgba(255,122,47,0.25) 0%, rgba(194,78,0,0.2) 100%)',
              backdropFilter: 'blur(20px) saturate(180%)',
              WebkitBackdropFilter: 'blur(20px) saturate(180%)',
              border: '1px solid rgba(255, 122, 47, 0.3)',
              color: '#7a2e00',
            }}
          >
            {product.category}
          </span>

          {/* Stats row */}
          <div className="flex items-center gap-5 mb-5">
            <div className="flex items-center gap-1.5">
              <span className="material-symbols-outlined text-primary" style={{ fontSize: '18px' }}>arrow_upward</span>
              <span className="text-sm font-black text-on-background">{product.votes.toLocaleString()}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="material-symbols-outlined text-primary" style={{ fontSize: '18px' }}>mode_comment</span>
              <span className="text-sm font-black text-on-background">{product.comments.toLocaleString()}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <span className="material-symbols-outlined text-primary" style={{ fontSize: '18px' }}>bolt</span>
              <span className="text-sm font-black text-primary">{product.score}</span>
            </div>
          </div>

          {/* Brief overview */}
          {product.briefOverview && (
            <p className="text-sm text-on-background/70 leading-relaxed mb-6">{product.briefOverview}</p>
          )}

          {/* Founder card */}
          {founder && (
            <div className="premium-glass rounded-2xl p-4 flex items-center gap-3">
              <div className="w-10 h-10 rounded-full overflow-hidden shadow-sm shrink-0 border border-white/60">
                <img src={founder.avatar} alt={founder.name} className="w-full h-full object-cover" />
              </div>
              <div>
                <p className="text-sm font-black text-on-background leading-tight">{founder.name}</p>
                <p className="text-xs text-on-background/60 font-semibold">{founder.role}</p>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Right column — scrollable content */}
      <div className="flex-1 space-y-8 fade-up fade-up-1">
        {/* Full description */}
        {product.description && (
          <div>
            <h2 className="text-xl font-black font-jakarta text-on-background mb-3">About</h2>
            {product.description.split('\n\n').map((paragraph, i) => (
              <p key={i} className="text-sm text-on-background/80 leading-relaxed mb-3">{paragraph}</p>
            ))}
          </div>
        )}

        {/* Product images */}
        {product.images.length > 0 && (
          <div className="space-y-4">
            {product.images.map((src, i) => (
              <div key={i} className="rounded-2xl overflow-hidden shadow-lg border border-orange-100/30">
                <img src={src} alt={`${product.name} screenshot ${i + 1}`} className="w-full object-cover" />
              </div>
            ))}
          </div>
        )}

        {/* Decode preview card */}
        {product.decodeUrl && (
          <DecodePreviewCard
            productName={product.name}
            description={`A deep-dive analysis of ${product.name}'s product strategy, technology stack, and competitive positioning generated by Apex.`}
            decodeUrl={product.decodeUrl}
          />
        )}

        {/* Rapid Course preview card */}
        {product.rapidCourseUrl && (
          <RapidCoursePreviewCard
            productName={product.name}
            description={`A hands-on microcourse covering ${product.name}'s core workflows, key concepts, and practical use cases generated by Apex.`}
            rapidCourseUrl={product.rapidCourseUrl}
          />
        )}
      </div>
    </div>
  )
}
