import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-fixed':             '#ff7a2f',
        'surface-container-high':    '#ffdcc6',
        'primary':                   '#9c3f00',
        'on-tertiary':               '#fff1df',
        'on-secondary':              '#fff0e8',
        'tertiary-container':        '#fbb423',
        'surface-container-lowest':  '#ffffff',
        'outline-variant':           '#dba078',
        'on-error':                  '#ffefec',
        'on-tertiary-fixed-variant': '#5e4000',
        'on-secondary-fixed':        '#552800',
        'surface-container-highest': '#ffd4b9',
        'tertiary-fixed-dim':        '#eba60f',
        'on-error-container':        '#520c00',
        'on-secondary-container':    '#723700',
        'surface-dim':               '#ffc9a6',
        'surface-variant':           '#ffd4b9',
        'tertiary-fixed':            '#fbb423',
        'on-background':             '#4a2506',
        'on-primary-fixed':          '#000000',
        'background':                '#fffaf7',
        'on-tertiary-fixed':         '#372400',
        'on-secondary-fixed-variant':'#803f00',
        'error-container':           '#f95630',
        'on-primary-container':      '#401500',
        'on-primary-fixed-variant':  '#4f1c00',
        'inverse-on-surface':        '#c99169',
        'surface':                   '#fffaf7',
        'on-surface':                '#4a2506',
        'tertiary-dim':              '#6b4900',
        'error':                     '#b02500',
        'tertiary':                  '#7a5400',
        'secondary-fixed':           '#ffc69f',
        'secondary':                 '#904800',
        'primary-dim':               '#893600',
        'surface-bright':            '#fffaf7',
        'inverse-primary':           '#fe6b00',
        'error-dim':                 '#b92902',
        'on-primary':                '#fff0ea',
        'secondary-dim':             '#7e3e00',
        'surface-container':         '#ffe3d2',
        'inverse-surface':           '#1c0900',
        'secondary-fixed-dim':       '#ffb37d',
        'surface-tint':              '#9c3f00',
        'on-tertiary-container':     '#523700',
        'primary-container':         '#ff7a2f',
        'on-surface-variant':        '#7f512e',
        'primary-fixed-dim':         '#f66700',
        'surface-container-low':     '#ffede4',
        'outline':                   '#9e6b47',
        'secondary-container':       '#ffc69f',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['var(--font-plus-jakarta-sans)', 'Plus Jakarta Sans', 'sans-serif'],
        body:     ['var(--font-inter)', 'Inter', 'sans-serif'],
        label:    ['var(--font-inter)', 'Inter', 'sans-serif'],
        jakarta:  ['var(--font-plus-jakarta-sans)', 'Plus Jakarta Sans', 'sans-serif'],
        vcr:      ['VCR OSD Mono', 'monospace'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}

export default config
